environment:
  ACCESS_TOKEN: ${ ACCESS_TOKEN }
  DEBUG: ${ DEBUG }
  DIGITALOCEAN_BASE_URL: ${ DIGITALOCEAN_BASE_URL }
  LOGTAIL_TOKEN: ${ LOGTAIL_TOKEN }
  OPENAI_API_KEY: ${ OPENAI_API_KEY }
  OPENAI_ASSISTANT_MODEL: ${ OPENAI_ASSISTANT_MODEL }
  OPENAI_IMAGE_SIZE: ${ OPENAI_IMAGE_SIZE }
  OPENAI_MODEL_TTS: ${ OPENAI_MODEL_TTS }
  OPENAI_ORG_ID: ${ OPENAI_ORG_ID }
  OPENAI_VOICE: ${ OPENAI_VOICE }
packages:
  - name: audio
    functions:
      - name: speech
        runtime: 'nodejs:18'
        limits:
          timeout: 60000
      - name: transcriptions
        runtime: 'nodejs:18'
        limits:
          timeout: 60000
  - name: files
    functions:
      - name: delete
        runtime: 'nodejs:18'
      - name: get
        runtime: 'nodejs:18'
      - name: list
        runtime: 'nodejs:18'
      - name: list-assistants
        runtime: 'nodejs:18'
      - name: list-assistants_output
        runtime: 'nodejs:18'
      - name: list-fine-tune
        runtime: 'nodejs:18'
      - name: list-fine-tune-results
        runtime: 'nodejs:18'
      - name: upload
        runtime: 'nodejs:18'
        limits:
          timeout: 60000
          memory: 512
  - name: images
    functions:
      - name: create
        runtime: 'nodejs:18'
        limits:
          timeout: 60000
  - name: messages
    functions:
      - name: create
        runtime: 'nodejs:18'
      - name: delete
        runtime: 'nodejs:18'
      - name: get
        runtime: 'nodejs:18'
      - name: list
        runtime: 'nodejs:18'
      - name: list-files
        runtime: 'nodejs:18'
      - name: update
        runtime: 'nodejs:18'
  - name: threads
    functions:
      - name: create
        runtime: 'nodejs:18'
      - name: delete
        runtime: 'nodejs:18'
      - name: get
        runtime: 'nodejs:18'
      - name: update
        runtime: 'nodejs:18'

